version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db_c
    environment:
      MYSQL_ROOT_PASSWORD: hello_world
      MYSQL_DATABASE: anilist_db
    ports:
      - "3307:3306"
    restart: always
    networks:
      - mynetwork 

  api:
    build: ./AniList
    container_name: api_c
    ports:
      - "8080:8080"
    depends_on:  
      - db  
    restart: always
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/anilist_db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=hello_world
      - ALLOWED_ORIGIN="http://localhost:4200"
    networks:
      - mynetwork 
  
  client:
    build: ./frontend-folder
    container_name: client_c
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    volumes:
      - ./frontend-folder:/app
      - /app/node_modules
    networks:
      - mynetwork

networks:
  mynetwork: 